version: "3.8"

env_file:
  - ../../.env

services:
  postgres:
    image: postgres:15
    container_name: go_api_pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: go_api_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
