services:
  app:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: go_api_app
    volumes:
      - ../..:/app
      - go-mod-cache:/go/pkg/mod
    command: reflex -c reflex.conf
    ports:
      - "${PORT}:8080"
    env_file:
      - ../../.env
    depends_on:
      - postgres
      - redis
    tty: true
    stdin_open: true
    working_dir: /app

  postgres:
    image: postgres:15
    container_name: go_api_pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: go_api_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
  go-mod-cache:
